### PR TITLE
Backwards-Compatible WAF Compliance

### PR DESCRIPTION
**Pull request by jpodwys**
@jakelheknight @tylergraf @dthorne I've tested this briefly on localhost and integration of the Memories app. Seeing as this needs to be merged in time for Monday morning's WAF test (probably should be merged first thing tomorrow morning), I would appreciate you reviewing and testing with Tree.

Thanks!

### CODE REVIEW

**Comment by tylergraf** [comment]
We don't use `ajaxBase` in anything that I know of, so we're ok I think.

**Comment by jakelheknight** [comment]
Looks good to me.

**Comment by jakelheknight** [comment]
We do when calling specific endpoints. Specifically when grabbing some photos form memories in pedigree.

**Comment by jakelheknight** [comment]
It is all in shared components though.

**Pull request merged**
